image: php:8.3

stages:
  - build
  - test

before_script:
  - apt-get update -y
  - apt-get install -y git unzip libzip-dev
  - docker-php-ext-install zip
  - pecl install pcov
  - docker-php-ext-enable pcov
  - echo "pcov.enabled=1" > /usr/local/etc/php/conf.d/pcov.ini
  - echo "pcov.directory=." >> /usr/local/etc/php/conf.d/pcov.ini
  - php -m | grep -i pcov
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install --no-interaction --prefer-dist
  - php artisan key:generate --env=testing

build:
  stage: build
  script:
    - echo "Build stage completed successfully"

tests:
  stage: test
  script:
    - php -d pcov.enabled=1  artisan test --env=testing --coverage

